name: Frontend

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - name: Setup Nodejs
      uses: actions/setup-node@v1
      with:
        node-version:  '13.x'
    
    - name: Install dependencies
      working-directory: ./js
      run: |
        make ci
    
    - name: Link protobuf
      run: |
        make link
    
    - name: Run build
      working-directory: ./js
      run: |
        make build
